name: build

on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12, 14]        
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Eduardo
        MIDDLE_NAME: Omar
        LAST_NAME: Mejia
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    
